
package com.atmira.formacion.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SecretariaServiceImpl", targetNamespace = "http://service.ws.secretariaIT.formacion.atmira.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SecretariaServiceImpl {


    /**
     * 
     * @param nombre
     * @param dni
     * @return
     *     returns int
     */
    @WebMethod(operationName = "AddProfesor")
    @WebResult(name = "Resultado", targetNamespace = "")
    @RequestWrapper(localName = "AddProfesor", targetNamespace = "http://service.ws.secretariaIT.formacion.atmira.com/", className = "com.atmira.formacion.wsclient.AddProfesor")
    @ResponseWrapper(localName = "AddProfesorResponse", targetNamespace = "http://service.ws.secretariaIT.formacion.atmira.com/", className = "com.atmira.formacion.wsclient.AddProfesorResponse")
    @Action(input = "http://service.ws.secretariaIT.formacion.atmira.com/SecretariaServiceImpl/AddProfesorRequest", output = "http://service.ws.secretariaIT.formacion.atmira.com/SecretariaServiceImpl/AddProfesorResponse")
    public int addProfesor(
        @WebParam(name = "dni", targetNamespace = "")
        String dni,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre);

    /**
     * 
     * @param dniProfesor
     * @param nombreAlumno
     * @param dniAlumno
     * @param nota
     * @return
     *     returns int
     */
    @WebMethod(operationName = "AddAlumno")
    @WebResult(name = "Resultado", targetNamespace = "")
    @RequestWrapper(localName = "AddAlumno", targetNamespace = "http://service.ws.secretariaIT.formacion.atmira.com/", className = "com.atmira.formacion.wsclient.AddAlumno")
    @ResponseWrapper(localName = "AddAlumnoResponse", targetNamespace = "http://service.ws.secretariaIT.formacion.atmira.com/", className = "com.atmira.formacion.wsclient.AddAlumnoResponse")
    @Action(input = "http://service.ws.secretariaIT.formacion.atmira.com/SecretariaServiceImpl/AddAlumnoRequest", output = "http://service.ws.secretariaIT.formacion.atmira.com/SecretariaServiceImpl/AddAlumnoResponse")
    public int addAlumno(
        @WebParam(name = "dniProfesor", targetNamespace = "")
        String dniProfesor,
        @WebParam(name = "dniAlumno", targetNamespace = "")
        String dniAlumno,
        @WebParam(name = "nombreAlumno", targetNamespace = "")
        String nombreAlumno,
        @WebParam(name = "nota", targetNamespace = "")
        double nota);

    /**
     * 
     * @param dni
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "Resultado", targetNamespace = "")
    @RequestWrapper(localName = "calcularPromedioProfesor", targetNamespace = "http://service.ws.secretariaIT.formacion.atmira.com/", className = "com.atmira.formacion.wsclient.CalcularPromedioProfesor")
    @ResponseWrapper(localName = "calcularPromedioProfesorResponse", targetNamespace = "http://service.ws.secretariaIT.formacion.atmira.com/", className = "com.atmira.formacion.wsclient.CalcularPromedioProfesorResponse")
    @Action(input = "http://service.ws.secretariaIT.formacion.atmira.com/SecretariaServiceImpl/calcularPromedioProfesorRequest", output = "http://service.ws.secretariaIT.formacion.atmira.com/SecretariaServiceImpl/calcularPromedioProfesorResponse")
    public double calcularPromedioProfesor(
        @WebParam(name = "dni", targetNamespace = "")
        String dni);

}
